site:
  title: Antora Docs
  start_page: component-a::index.adoc
content:
  sources:
    - url: https://github.com/analiceleite/antora_test.git
      branches: main
      start_path: components/component-a
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
